### ISSUE TITLE
do r2_diff function accepts covariates as input?

### ISSUE THREAD

**Issue by WeiCSong** [mommy003/r2redux#1]
Hi, thanks for the great tool! I notice that v1 and v2 arguments of r2_diff function accepts multiple columns as input, so can I include covariate columns? for example,

`r2_diff(dat, v1=c("PGS1","age","sex"), v2=c("PGS2","age",sex"))`

will this generate comparison result controlling age and sex effects? Thanks for your help!

**Comment by mommy003** [comment]
Hi, thanks for your interest in our work.

You can test differences of R2 between v1=c("PGS1","age","sex") and v2=c("PGS2","age",sex")). I checked it with extensive simulation for quantitative, binary, and case-control traits (with various values for prevalence). We observed a similar variance of R2 between models (y_adj=PGS+e Vs.  y=PGS+cov_1+cov_2; where y_adj is pre-adjusted y  for cov_1 and cov_2, i.e. residuals from y = cov_1 + cov_2).

So, you can use either approach.
v1=c("PGS1","age","sex") and v2=c("PGS2","age",sex") with raw y
v1=c("PGS1") and v2=c("PGS2") with pre-adjusted y_adj

Please note that R^2 can be slightly reduced when using pre-adjusted y (adjusted for covariates in the first step) although the test statistic may not be substantially changed. For our analyses, we used pre-adjusted y.

Please let us know if you have further questions or comments.
Momin

**Comment by WeiCSong** [comment]
> Hi, thanks for your interest in our work.
> 
> You can test differences of R2 between v1=c("PGS1","age","sex") and v2=c("PGS2","age",sex")). I checked it with extensive simulation for quantitative, binary, and case-control traits (with various values for prevalence). We observed a similar variance of R2 between models (y_adj=PGS+e Vs. y=PGS+cov_1+cov_2; where y_adj is pre-adjusted y for cov_1 and cov_2, i.e. residuals from y = cov_1 + cov_2).
> 
> So, you can use either approach. v1=c("PGS1","age","sex") and v2=c("PGS2","age",sex") with raw y v1=c("PGS1") and v2=c("PGS2") with pre-adjusted y_adj
> 
> Please note that R^2 can be slightly reduced when using pre-adjusted y (adjusted for covariates in the first step) although the test statistic may not be substantially changed. For our analyses, we used pre-adjusted y.
> 
> Please let us know if you have further questions or comments. Momin

Got it! I'll pre-adjust y, Thanks for your help!
