### ISSUE TITLE
Can this package be used to compare PRSs from the same GWAS but different methods?

### ISSUE THREAD

**Issue by gunns2** [mommy003/r2redux#2]
Hi,
Thank you for this great resource!!
I see that this package can be used to compare PRSs that come from different discovery sets, and for PRSs that are nested, but what about PRSs that use the same base GWAS set but come from different models or even different LD panels?

Thanks so much!

**Comment by mommy003** [comment]
Hi,

Thanks for your interest in r2redux.

Yes, you can test PRSs that use the same base GWAS set but come from different models or even different LD panels.
Please see the manuscript in the following link, we estimated significant differences between different p-value thresholds (similar to your approach).
https://authors.elsevier.com/a/1gUCageX6KJk 

Even you can test two significant differences between two independent PRS (e.g., male vs female).

Let me know if you need further information.

Regards

**Comment by gunns2** [comment]
Thank you for your quick reply! So the function r2_diff can be used regardless of correlation structure between the two scores? 

thanks!
Sophie

**Comment by mommy003** [comment]
Yes. 

r2_diff considers correlation structures between PGS to estimate variance differences and compute 95% CI.
Let me know if you have any queries.

Thanks

**Comment by gunns2** [comment]
Great, thanks so much!
